server:
  port: 5000
  servlet:
    context-path: /minesweeper-api


spring:
  data:
    mongodb:
      uri: ${MONGODB_URI}


springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /documentation.html